version: "3.8"

services:
  app1:
    build: ./app
    container_name: app1
    environment:
      - INSTANCE_ID=APP-1
    expose:
      - "5000"

  app2:
    build: ./app
    container_name: app2
    environment:
      - INSTANCE_ID=APP-2
    expose:
      - "5000"

  app3:
    build: ./app
    container_name: app3
    environment:
      - INSTANCE_ID=APP-3
    expose:
      - "5000"

  nginx:
    image: nginx:1.27-alpine
    container_name: nginx-lb
    ports:
      - "8080:80"
    depends_on:
      - app1
      - app2
      - app3
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
